use std::collections::BTreeMap;

use kairo_core::{
    ClusterEvent,
    models::{ContainerStatus, PodDetail, PodEvent, PodSummary},
};

pub fn pods() -> Vec<PodSummary> {
    vec![
        PodSummary {
            name: "api-server-7d9f8b-xk2p4".to_string(),
            namespace: "production".to_string(),
            status: "Running".to_string(),
            ready: "2/2".to_string(),
            restarts: 0,
            age: "5d".to_string(),
            node: "node-01".to_string(),
            labels: BTreeMap::from([
                ("app".to_string(), "api-server".to_string()),
                ("version".to_string(), "v1.4.2".to_string()),
            ]),
            owner_kind: "ReplicaSet".to_string(),
            owner_name: "api-server-7d9f8b".to_string(),
            container_names: vec!["api-server".to_string(), "envoy-proxy".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "worker-6c8d9f-m3n7k".to_string(),
            namespace: "production".to_string(),
            status: "Running".to_string(),
            ready: "1/1".to_string(),
            restarts: 2,
            age: "2d".to_string(),
            node: "node-02".to_string(),
            labels: BTreeMap::from([("app".to_string(), "worker".to_string())]),
            owner_kind: "Deployment".to_string(),
            owner_name: "worker".to_string(),
            container_names: vec!["worker".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "database-0".to_string(),
            namespace: "production".to_string(),
            status: "Running".to_string(),
            ready: "1/1".to_string(),
            restarts: 0,
            age: "14d".to_string(),
            node: "node-03".to_string(),
            labels: BTreeMap::from([("app".to_string(), "database".to_string())]),
            owner_kind: "StatefulSet".to_string(),
            owner_name: "database".to_string(),
            container_names: vec!["postgres".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "cache-557b9c-v8pq2".to_string(),
            namespace: "production".to_string(),
            status: "CrashLoopBackOff".to_string(),
            ready: "0/1".to_string(),
            restarts: 14,
            age: "1h".to_string(),
            node: "node-01".to_string(),
            labels: BTreeMap::from([("app".to_string(), "cache".to_string())]),
            owner_kind: "ReplicaSet".to_string(),
            owner_name: "cache-557b9c".to_string(),
            container_names: vec!["redis".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "job-batch-abc12".to_string(),
            namespace: "jobs".to_string(),
            status: "Pending".to_string(),
            ready: "0/1".to_string(),
            restarts: 0,
            age: "5m".to_string(),
            node: "".to_string(),
            labels: BTreeMap::from([("job-name".to_string(), "batch-processor".to_string())]),
            owner_kind: "Job".to_string(),
            owner_name: "batch-processor".to_string(),
            container_names: vec!["processor".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "ingress-nginx-c7b9d-kl5p3".to_string(),
            namespace: "ingress-nginx".to_string(),
            status: "Running".to_string(),
            ready: "1/1".to_string(),
            restarts: 0,
            age: "30d".to_string(),
            node: "node-02".to_string(),
            labels: BTreeMap::from([
                ("app.kubernetes.io/name".to_string(), "ingress-nginx".to_string()),
                ("app.kubernetes.io/component".to_string(), "controller".to_string()),
            ]),
            owner_kind: "DaemonSet".to_string(),
            owner_name: "ingress-nginx".to_string(),
            container_names: vec!["controller".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "prometheus-0".to_string(),
            namespace: "monitoring".to_string(),
            status: "Running".to_string(),
            ready: "2/2".to_string(),
            restarts: 1,
            age: "7d".to_string(),
            node: "node-03".to_string(),
            labels: BTreeMap::from([
                ("app".to_string(), "prometheus".to_string()),
                ("release".to_string(), "kube-prom-stack".to_string()),
            ]),
            owner_kind: "StatefulSet".to_string(),
            owner_name: "prometheus".to_string(),
            container_names: vec!["prometheus".to_string(), "config-reloader".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "grafana-8b7d6c-wx4m9".to_string(),
            namespace: "monitoring".to_string(),
            status: "Running".to_string(),
            ready: "1/1".to_string(),
            restarts: 0,
            age: "7d".to_string(),
            node: "node-01".to_string(),
            labels: BTreeMap::from([(
                "app.kubernetes.io/name".to_string(),
                "grafana".to_string(),
            )]),
            owner_kind: "ReplicaSet".to_string(),
            owner_name: "grafana-8b7d6c".to_string(),
            container_names: vec!["grafana".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "cert-manager-84f9b-rm7x2".to_string(),
            namespace: "cert-manager".to_string(),
            status: "Running".to_string(),
            ready: "1/1".to_string(),
            restarts: 0,
            age: "21d".to_string(),
            node: "node-02".to_string(),
            labels: BTreeMap::from([
                ("app".to_string(), "cert-manager".to_string()),
                (
                    "app.kubernetes.io/component".to_string(),
                    "controller".to_string(),
                ),
            ]),
            owner_kind: "ReplicaSet".to_string(),
            owner_name: "cert-manager-84f9b".to_string(),
            container_names: vec!["cert-manager".to_string()],
            references: vec![],
        },
        PodSummary {
            name: "oom-killed-job-abc99".to_string(),
            namespace: "jobs".to_string(),
            status: "OOMKilled".to_string(),
            ready: "0/1".to_string(),
            restarts: 3,
            age: "2h".to_string(),
            node: "node-03".to_string(),
            labels: BTreeMap::from([("job-name".to_string(), "memory-hog".to_string())]),
            owner_kind: "Job".to_string(),
            owner_name: "memory-hog".to_string(),
            container_names: vec!["worker".to_string()],
            references: vec![],
        },
    ]
}

pub fn pod_detail() -> PodDetail {
    PodDetail {
        summary: PodSummary {
            name: "api-server-7d9f8b-xk2p4".to_string(),
            namespace: "production".to_string(),
            status: "Running".to_string(),
            ready: "2/2".to_string(),
            restarts: 0,
            age: "5d".to_string(),
            node: "node-01".to_string(),
            labels: BTreeMap::from([
                ("app".to_string(), "api-server".to_string()),
                ("version".to_string(), "v1.4.2".to_string()),
                ("pod-template-hash".to_string(), "7d9f8b".to_string()),
            ]),
            owner_kind: "ReplicaSet".to_string(),
            owner_name: "api-server-7d9f8b".to_string(),
            container_names: vec!["api-server".to_string(), "envoy-proxy".to_string()],
            references: vec![],
        },
        labels: BTreeMap::from([
            ("app".to_string(), "api-server".to_string()),
            ("version".to_string(), "v1.4.2".to_string()),
            ("pod-template-hash".to_string(), "7d9f8b".to_string()),
        ]),
        annotations: BTreeMap::from([
            (
                "kubectl.kubernetes.io/last-applied-configuration".to_string(),
                "{...}".to_string(),
            ),
            ("prometheus.io/scrape".to_string(), "true".to_string()),
            ("prometheus.io/port".to_string(), "9090".to_string()),
        ]),
        containers: vec![
            ContainerStatus {
                name: "api-server".to_string(),
                image: "registry.example.com/api-server:v1.4.2".to_string(),
                ready: true,
                restart_count: 0,
                state: "Running".to_string(),
            },
            ContainerStatus {
                name: "envoy-proxy".to_string(),
                image: "envoyproxy/envoy:v1.28.0".to_string(),
                ready: true,
                restart_count: 0,
                state: "Running".to_string(),
            },
        ],
        events: vec![
            PodEvent {
                reason: "Scheduled".to_string(),
                message: "Successfully assigned production/api-server-7d9f8b-xk2p4 to node-01"
                    .to_string(),
                event_type: "Normal".to_string(),
                count: 1,
                first_time: "2024-01-15T10:00:00Z".to_string(),
                last_time: "2024-01-15T10:00:00Z".to_string(),
            },
            PodEvent {
                reason: "Pulled".to_string(),
                message:
                    "Successfully pulled image \"registry.example.com/api-server:v1.4.2\""
                        .to_string(),
                event_type: "Normal".to_string(),
                count: 1,
                first_time: "2024-01-15T10:00:05Z".to_string(),
                last_time: "2024-01-15T10:00:05Z".to_string(),
            },
            PodEvent {
                reason: "Started".to_string(),
                message: "Started container api-server".to_string(),
                event_type: "Normal".to_string(),
                count: 1,
                first_time: "2024-01-15T10:00:08Z".to_string(),
                last_time: "2024-01-15T10:00:08Z".to_string(),
            },
        ],
    }
}

pub fn cluster_events() -> Vec<ClusterEvent> {
    vec![
        ClusterEvent {
            namespace: "production".to_string(),
            object_kind: "Pod".to_string(),
            object_name: "cache-557b9c-v8pq2".to_string(),
            reason: "BackOff".to_string(),
            message: "Back-off restarting failed container redis in pod cache-557b9c-v8pq2_production".to_string(),
            event_type: "Warning".to_string(),
            count: 14,
            last_time: "2024-01-15T11:30:00Z".to_string(),
        },
        ClusterEvent {
            namespace: "jobs".to_string(),
            object_kind: "Pod".to_string(),
            object_name: "oom-killed-job-abc99".to_string(),
            reason: "OOMKilling".to_string(),
            message: "Memory limit reached. Killing container memory-hog with 512Mi limit".to_string(),
            event_type: "Warning".to_string(),
            count: 3,
            last_time: "2024-01-15T11:00:00Z".to_string(),
        },
        ClusterEvent {
            namespace: "production".to_string(),
            object_kind: "Deployment".to_string(),
            object_name: "worker".to_string(),
            reason: "ScalingReplicaSet".to_string(),
            message: "Scaled up replica set worker-6c8d9f from 2 to 3".to_string(),
            event_type: "Normal".to_string(),
            count: 1,
            last_time: "2024-01-15T10:45:00Z".to_string(),
        },
        ClusterEvent {
            namespace: "kube-system".to_string(),
            object_kind: "Node".to_string(),
            object_name: "node-03".to_string(),
            reason: "NodeNotReady".to_string(),
            message: "Node node-03 status is now: NodeNotReady".to_string(),
            event_type: "Warning".to_string(),
            count: 1,
            last_time: "2024-01-15T09:15:00Z".to_string(),
        },
        ClusterEvent {
            namespace: "cert-manager".to_string(),
            object_kind: "Certificate".to_string(),
            object_name: "api-tls".to_string(),
            reason: "Failed".to_string(),
            message: "Failed to obtain certificate: acme: error: 403 :: urn:ietf:params:acme:error:unauthorized".to_string(),
            event_type: "Warning".to_string(),
            count: 5,
            last_time: "2024-01-15T08:00:00Z".to_string(),
        },
    ]
}

pub fn log_lines() -> Vec<String> {
    vec![
        "2024-01-15T10:00:08.123Z INFO  Starting API server on :8080".to_string(),
        "2024-01-15T10:00:08.456Z INFO  Connecting to database at postgres://db:5432/api".to_string(),
        "2024-01-15T10:00:09.001Z INFO  Database connection established (pool_size=10)".to_string(),
        "2024-01-15T10:00:09.234Z INFO  Loading configuration from /etc/api/config.yaml".to_string(),
        "2024-01-15T10:00:09.345Z INFO  Registering health check endpoints".to_string(),
        "2024-01-15T10:00:09.456Z INFO  Server ready. Listening on :8080".to_string(),
        "2024-01-15T10:01:02.789Z INFO  GET /api/v1/users 200 OK (12ms) addr=10.244.0.5".to_string(),
        "2024-01-15T10:01:05.012Z INFO  GET /api/v1/items 200 OK (8ms) addr=10.244.0.3".to_string(),
        "2024-01-15T10:01:07.234Z WARN  Slow query detected: 450ms SELECT * FROM orders WHERE user_id=...".to_string(),
        "2024-01-15T10:01:10.567Z INFO  POST /api/v1/orders 201 Created (35ms) addr=10.244.0.5".to_string(),
        "2024-01-15T10:01:15.890Z ERROR Failed to connect to cache: dial tcp 10.96.0.15:6379: connection refused".to_string(),
        "2024-01-15T10:01:15.891Z WARN  Falling back to in-memory cache (TTL=60s)".to_string(),
        "2024-01-15T10:01:20.123Z INFO  GET /healthz 200 OK (0ms) addr=10.244.0.1".to_string(),
        "2024-01-15T10:01:25.456Z INFO  GET /api/v1/metrics 200 OK (5ms) addr=10.244.0.2".to_string(),
        "2024-01-15T10:01:30.789Z INFO  Background job: cleaning expired sessions (removed=23)".to_string(),
        "2024-01-15T10:01:35.012Z INFO  GET /api/v1/users/42 200 OK (9ms) addr=10.244.0.5".to_string(),
        "2024-01-15T10:01:40.345Z INFO  Cache miss for key user:42:profile, fetching from db".to_string(),
        "2024-01-15T10:01:40.678Z INFO  Cache populated for key user:42:profile (TTL=300s)".to_string(),
        "2024-01-15T10:01:45.901Z INFO  GET /api/v1/users/42 200 OK (2ms) addr=10.244.0.5".to_string(),
        "2024-01-15T10:01:50.234Z INFO  Worker heartbeat: queue_depth=12 processed=847".to_string(),
    ]
}
